
set(CMAKE_AUTOUIC ON)
set(CMAKE_AUTOMOC ON)
set(CMAKE_AUTORCC ON)
set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

set(SOFT_DEVELOPER "PeeceKeeper42")
set(DEVELOPER_DOMAIN "github.com/PeeceKeeper42")
set(ROOT_PROJECT_DIR ${CMAKE_CURRENT_SOURCE_DIR}/..)
set(RESOURCES_DIR ${ROOT_PROJECT_DIR}/_resources)




