
if (${CMAKE_SIZEOF_VOID_P} STREQUAL 4)
    set(DIR_PREFIX "x86")
elseif (${CMAKE_SIZEOF_VOID_P} STREQUAL 8)
    set(DIR_PREFIX "x64")
endif ()

set(DISTRIB_DIR ${ROOT_PROJECT_DIR}/_distrib/lin_${QT_VERSION}_${DIR_PREFIX})
set(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${DISTRIB_DIR}/bin)
set(LIB_DIRECTORY ${DISTRIB_DIR}/lib)
set(MOD_DIRECTORY ${DISTRIB_DIR}/modules)
